pipeline {
    agent { label 'JNKS' }
    triggers { pollSCM('* * * * *') }
    stages { 
        stage('clone') {
            steps {
                
                git branch: 'main', url: 'https://github.com/GUDAPATIVENKATESH/spring-petclinic.git'
            }
        }
        stage('sonarQubeAnalysis') {
            steps {
                withSonarQubeEnv('SONAR') {
                    sh " mvn clean package sonar:sonar"
                }
            }
        }
        stage ('Artifactory configuration') {
            steps {
               rtMavenDeployer (
                    id: "MAVEN_HOME",
                    serverId: "JFROG_TASK",
                    releaseRepo: "https://cicdrj.jfrog.io/artifactory/libs-release",
                    snapshotRepo: "https://cicdrj.jfrog.io/artifactory/libs-snapshot"
                )
            }
        }
        stage ('Exec Maven') {
            steps {
                rtMavenRun (
                    tool: "MAVEN_HOME", // Tool name from Jenkins configuration
                    pom: 'pom.xml',
                    goals: 'clean install',
                )
            }
        }
        stage ('Publish build info') {
            steps {
                rtPublishBuildInfo (
                    serverId: "JFROG_TASK"
                )
            }
        }
    }
    post { 
        always { 
            mail subject: "Build started for Jenkins JOB $env.JOB_NAME", 
                  body: "Build started for Jenkins JOB $env.JOB_NAME \n Click Here: $env.JOB_URL", 
                  to: 'qtdevops@gmail.com'
        }
        failure {
            mail subject: "Build faild for Jenkins JOB $env.JOB_NAME", 
                  body: "Build faild for Jenkins JOB $env.JOB_NAME \n Click Here: $env.JOB_URL", 
                  to: 'qtdevops@gmail.com'
        }
        finally {
            mail subject: "Build Completed for Jenkins JOB $env.JOB_NAME", 
                  body: "Build Completed for Jenkins JOB $env.JOB_NAME \n Click Here: $env.JOB_URL", 
                  to: 'qtdevops@gmail.com'
        }
    }
}